# Generated by Django 4.1.7 on 2023-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='target',
            name='scheme',
            field=models.CharField(choices=[('http', 'Http'), ('https', 'Https')], default='http', max_length=64),
        ),
        migrations.AlterField(
            model_name='upstream',
            name='scheme',
            field=models.CharField(choices=[('http', 'Http'), ('https', 'Https')], default='http', max_length=64),
        ),
    ]
