# Generated by Django 4.1.7 on 2023-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apigateway", "0002_alter_user_options_alter_target_scheme_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminApi",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apigateway.api",),
        ),
        migrations.CreateModel(
            name="BasicApi",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apigateway.api",),
        ),
        migrations.CreateModel(
            name="DefaultApi",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apigateway.api",),
        ),
        migrations.CreateModel(
            name="ETCApi",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apigateway.api",),
        ),
        migrations.CreateModel(
            name="KeyApi",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apigateway.api",),
        ),
        migrations.AddField(
            model_name="target",
            name="port",
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name="upstream",
            name="port",
            field=models.IntegerField(default=80),
        ),
    ]
