# Generated by Django 4.1.7 on 2023-04-11 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apigateway", "0003_adminapi_basicapi_defaultapi_etcapi_keyapi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="target",
            name="port",
        ),
        migrations.RemoveField(
            model_name="upstream",
            name="port",
        ),
    ]
