# Generated by Django 4.1.7 on 2023-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('path_info', models.TextField()),
                ('method', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 날짜')),
            ],
        ),
    ]
