# Generated by Django 4.1.7 on 2023-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
