# Generated by Django 4.1.7 on 2023-03-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirectionpage',
            old_name='request_path',
            new_name='requested_path',
        ),
    ]
